; --- ENVIRONMENT 1: THE GARDENER (TTGO) ---
[env:ttgo-lora32-v1]
platform = espressif32
board = ttgo-lora32-v1
framework = arduino
monitor_speed = 115200
build_flags = -I include
lib_deps =
    mobizt/Firebase Arduino Client Library for ESP8266 and ESP32 @ ^4.4.8
    ; Add other plant libs here 

; Only compile the plant code!
src_filter = +<plant_node.cpp>


; --- ENVIRONMENT 2: THE PHOTOGRAPHER (Freenove WROVER) ---
[env:freenove_camera]
platform = espressif32
board = esp-wrover-kit
framework = arduino
monitor_speed = 115200
upload_speed = 921600
build_flags = 
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-strategy=memw
    -I include

lib_deps =
    ; Only libraries needed for the camera
    esp32-camera
    mobizt/Firebase Arduino Client Library for ESP8266 and ESP32 @ ^4.4.8

; Only compile the camera code!
src_filter = +<camera_node.cpp>